name: cashor_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  appwrite: ^9.0.0
  barcode_scan2: ^4.2.4
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  discord_logger: ^1.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^4.0.4
  image_picker: ^0.8.7+5
  intl: ^0.18.1
  introduction_screen: ^3.1.8
  qr_flutter: ^4.1.0
  share_plus: ^7.0.2
  timeago: ^3.4.0
  webview_flutter: ^4.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
